### ISSUE TITLE
IO Generator (CRUD)  _detail.php not generated?

### ISSUE THREAD

**Issue by jobsrey** [mootensai/yii2-enhanced-gii#100]
How to generate _detail.php, because your module is confuse? 
Please, make it more complete documentation.
Thx

**Comment by mootensai** [comment]
just check expandable.. Yeah, I haven't think about improving the documentation..

**Comment by jobsrey** [comment]
Oh ok,, this my setting
![selection_016](https://cloud.githubusercontent.com/assets/25948056/23842420/be90b3b2-07e6-11e7-8f89-9c5893c4ad10.png)

And result

![selection_015](https://cloud.githubusercontent.com/assets/25948056/23842427/cafbf486-07e6-11e7-8839-d3652e417ab6.png)

![selection_017](https://cloud.githubusercontent.com/assets/25948056/23842473/0c00d4a6-07e7-11e7-832b-6324d021ff59.png)

maybe you must fix this..

**Comment by mootensai** [comment]
Could you send your database dump?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: jobsreySent: Senin, 13 Maret 2017 12.17To: mootensai/yii2-enhanced-giiReply To: mootensai/yii2-enhanced-giiCc: Yohanes Candrajaya; CommentSubject: Re: [mootensai/yii2-enhanced-gii] IO Generator (CRUD) _detail.php not generated? (#100)Oh ok,, this my setting

And result


maybe you must fix this..

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mootensai/yii2-enhanced-gii","title":"mootensai/yii2-enhanced-gii","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mootensai/yii2-enhanced-gii"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jobsrey in #100: Oh ok,, this my setting\r\n![selection_016](https://cloud.githubusercontent.com/assets/25948056/23842420/be90b3b2-07e6-11e7-8f89-9c5893c4ad10.png)\r\n\r\nAnd result\r\n\r\n![selection_015](https://cloud.githubusercontent.com/assets/25948056/23842427/cafbf486-07e6-11e7-8839-d3652e417ab6.png)\r\n\r\n![selection_017](https://cloud.githubusercontent.com/assets/25948056/23842473/0c00d4a6-07e7-11e7-832b-6324d021ff59.png)\r\n\r\nmaybe you must fix this..\r\n"}],"action":{"name":"View Issue","url":"https://github.com/mootensai/yii2-enhanced-gii/issues/100#issuecomment-286017571"}}}

**Comment by jobsrey** [comment]
My table is self relation in key parent_id, this my query
```
CREATE TABLE `ak_location` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `address1` text,
  `address2` text,
  `address3` text,
  `address4` text,
  `created_at` int(11) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_at` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `id_parent` int(11) NOT NULL,
  `id_company` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
```
how to use your module with my table?
thx yohanes

**Comment by mootensai** [comment]
Then that's the reason why you don't generate _detail.php

_detail.php only generated on models that have children table(s)..

**Comment by mootensai** [comment]
Thanks!! it's fixed now..
